;;; tessera-mu4e-headers-tests.el --- Native rows -*- lexical-binding: t; -*-

;;; Commentary:

;; Exercise native row identity, mark edits, and reversible layouts.

;;; Code:

(require 'ert)
(require 'mu4e-headers)
(require 'tessera-mu4e)
(require 'tessera-mu4e-headers)

(ert-deftest tessera-mu4e-contacts-use-names-with-address-fallback ()
  (let ((mu4e-headers-from-or-to-prefix '("From: " . "To: ")))
    (cl-letf (((symbol-function 'mu4e-server-properties)
               (lambda () '(:personal-addresses
                            ("self@example.test")))))
      (dolist (spec
               '(((:name "Alex Jr." :email "alex@example.test")
                  nil "Alex Jr.")
                 ((:email "alex@example.test")
                  nil "alex@example.test")
                 ((:name "" :email "alex@example.test")
                  nil "alex@example.test")
                 ((:name "Self" :email "self@example.test")
                  ((:name "李明" :email "li@example.test")
                   (:name "José" :email "jose@example.test"))
                  "李明, José")
                 ((:name "Self" :email "self@example.test")
                  ((:email "li@example.test")) "li@example.test")))
        (let* ((message (list :from (list (car spec)) :to (cadr spec)
                              :flags '(unread)))
               (context (tessera-mu4e-headers--context
                         message nil nil))
               (text (tessera-mu4e-headers--field 'contact context)))
          (should (equal text (nth 2 spec)))
          (should (equal (get-text-property 0 'face text)
                         'tessera-mu4e-headers-unread-contact-face))
          (should (string-match-p
                   (regexp-quote (plist-get (car spec) :email))
                   (get-text-property 0 'help-echo text)))
          (should (eq (get-text-property 0 'mouse-face text)
                      'tessera-entry-hover-face))))
      (should (equal mu4e-headers-from-or-to-prefix
                     '("From: " . "To: "))))))

(ert-deftest tessera-mu4e-headers-preserve-native-operations ()
  (let ((mu4e-search-threads nil)
        (mu4e-headers-mode-hook nil)
        (mu4e-headers-fields '((:subject)))
        (mu4e-search-hide-enabled nil)
        (message '(:docid 42 :subject "Native subject"
                          :from ((:name "Sender"
                                        :email "a@example.test"))
                          :date (27000 0) :flags (unread attach)
                          :priority high :tags ("foo" "bar"))))
    (with-temp-buffer
      (mu4e-headers-mode)
      (let ((inhibit-read-only t)
            (buffer (current-buffer)))
        (cl-letf (((symbol-function 'mu4e-get-headers-buffer)
                   (lambda (&rest _) buffer)))
          (mu4e~headers-insert-header message (point-min))
          (goto-char (point-min))
          (mu4e-mark-at-point 'unmark nil)
          (let ((native (buffer-string)))
            (tessera-mu4e--enable-headers)
            (dolist (layout '(single-line two-line))
              (setq-local tessera-entry-layout layout)
              (tessera-mu4e-headers--refresh)
              (should (= 1 (count-lines (point-min) (point-max))))
              (should (mu4e~headers-goto-docid 42))
              (should (equal message (mu4e-message-at-point)))
              (should (get-text-property
                       (tessera-mu4e-headers--body-start)
                       'tessera-mu4e-native)))
            (mu4e-mark-at-point 'move "/archive")
            (tessera-mu4e-headers--refresh)
            (should (equal (gethash 42 mu4e--mark-map)
                           '(move . "/archive")))
            (should (string-match-p "→ /archive" (buffer-string)))
            (tessera-mu4e-headers--disable)
            (should (cl-some (lambda (overlay)
                               (overlay-get overlay 'mu4e-mark))
                             (overlays-in (point-min) (point-max))))
            (mu4e-mark-at-point 'unmark nil)
            (should (equal-including-properties
                     native (buffer-string)))
            (tessera-mu4e--enable-headers)
            (let ((mu4e-search-threads t))
              (tessera-mu4e-headers--refresh)
              (should (string-match-p "1/1Native subject"
                                      (buffer-string))))
            (tessera-mu4e-headers--refresh)
            (mu4e~headers-remove-header 42)
            (setq message (plist-put message :flags '(seen)))
            (mu4e~headers-insert-header message (point-min))
            (goto-char (point-min))
            (tessera-mu4e-headers--refresh)
            (should (equal message (mu4e-message-at-point)))
            (tessera-mu4e-headers--disable)
            (dolist (overlay (overlays-in (point-min) (point-max)))
              (should (eq (overlay-get overlay 'face)
                          hl-line-face)))))))))

(ert-deftest tessera-mu4e-headers-navigate-logical-entries ()
  (let ((mu4e-search-threads nil)
        (mu4e-headers-mode-hook nil)
        (mu4e-headers-fields '((:subject)))
        (mu4e-search-hide-enabled nil)
        (mu4e-headers-open-after-move nil))
    (with-temp-buffer
      (mu4e-headers-mode)
      (let ((inhibit-read-only t)
            (buffer (current-buffer)))
        (cl-letf (((symbol-function 'mu4e-get-headers-buffer)
                   (lambda (&rest _) buffer)))
          (dotimes (index 3)
            (mu4e~headers-insert-header
             (list :docid (1+ index) :subject "Subject"
                   :from '((:name "Author" :email "a@example.test"))
                   :date '(27000 0) :flags '(seen))
             (point-max)))
          (dolist (local '(nil t))
            (when local
              (setq-local line-move-ignore-invisible t))
            (let ((before line-move-ignore-invisible))
              (tessera-mu4e--enable-headers)
              (dolist (tessera-entry-layout '(single-line two-line))
                (tessera-mu4e-headers--refresh)
                (mu4e~headers-goto-docid 2)
                (should (= 1 (call-interactively (key-binding "p"))))
                (should (looking-at "Subject"))
                (should (= 2 (call-interactively (key-binding "n"))))
                (should (looking-at "Subject"))
                (should (= 3 (mu4e-headers-next)))
                (should (looking-at "Subject"))
                (should (= 1 (mu4e-headers-prev 2)))
                (should (looking-at "Subject"))
                (let* ((message (copy-sequence
                                 (mu4e-message-at-point)))
                       (flags (if (memq 'seen
                                        (plist-get message :flags))
                                  '(unread replied flagged)
                                '(seen))))
                  (mu4e~headers-update-handler
                   (plist-put message :flags flags) nil nil)
                  (should (= 1 (mu4e~headers-docid-at-point)))
                  (should (looking-at "Subject"))
                  (should (= (point) (tessera-entry-point)))))
              (tessera-mu4e-headers--disable)
              (should (= 2 (mu4e-headers-next)))
              (should (= 2 (current-column)))
              (should (eq before line-move-ignore-invisible))
              (should (eq local (local-variable-p
                                 'line-move-ignore-invisible))))))))))

(ert-deftest tessera-mu4e-headers-labels-keep-neutral-separators ()
  (let* ((mu4e--mark-map (make-hash-table))
         (message '(:flags (seen) :labels ("foo" "bar")
                           :tags ("bar" "baz")))
         (context (tessera-mu4e-headers--context message nil nil))
         (text (tessera-mu4e-headers--field 'labels context)))
    (should (equal text "foo,bar,baz"))
    (should (equal (get-text-property 4 'help-echo text)
                   "bar (label, tag)"))
    (dolist (position '(3 7))
      (should (eq (get-text-property position 'mouse-face text)
                  'default))
      (should (eq (get-text-property position 'face text) 'default)))
    (should (equal (plist-get message :labels) '("foo" "bar")))))

(provide 'tessera-mu4e-headers-tests)
;;; tessera-mu4e-headers-tests.el ends here
